### ISSUE TITLE
returning response code 400 

### ISSUE THREAD

**Issue by heihitesh** [Jakebreen/android-sendgrid#10]
```mail.setTemplateId(@NonNull String templateId)
mail.setDynamicTemplateData(@NonNull JSONObject jsonObject)

// JSONObject structured into key/value pairs
final JSONObject templateData = new JSONObject();
templateData.put("forename", "Jane");
templateData.put("surname", "Doe");
templateData.put("message", "Hello, This is my email");

mail.setDynamicTemplateData(templateData)

```
This returning response code 400

**Comment by jakebreen** [comment]
Is there an error message with it? The message will be included as part of the response `SendGridResponse.getErrorMessage()`.

Can you please include the Json object and it's elements you are trying to send?

**Comment by heihitesh** [comment]
```SendGridMail mail = new SendGridMail();
        mail.addRecipient(email, name);
        mail.setFrom("binaryDev101@gmail.com", "Rent House Manager Pro");
        mail.setSubject("Welcome to Rent House Manager Pro");
         mail.setTemplateId("API");
      
// JSONObject structured into key/value pairs
        final JSONObject templateData = new JSONObject();
       try {
            templateData.put("forename", "Hitesh Verma");
           mail.setDynamicTemplateData(templateData);
        } catch (JSONException e) {
            e.printStackTrace();
        }

 SendTask task = new SendTask(sendGrid, mail);
        try {
            SendGridResponse response = task.execute().get();
            toastHelper.toastInfoMsg("Code " + response.getCode());
        } catch (ExecutionException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
```

Is this correct?

**Comment by jakebreen** [comment]
Looks OK. What message is returned from the response in the logcat if you _Log_ it?

```
try {
      SendGridResponse response = task.execute().get();
      Log.d("Response", response.getErrorMessage());
}
```

**Comment by jakebreen** [comment]
I've ran the code you've provided and I do indeed get an error message:

_"Unless a valid template_id is provided, the content parameter is required. There must be at least one defined content block. We typically suggest both text/plain and text/html blocks are included, but only one block is required."_

This is because the content of the mail has not been set, and requires a value even though you are using a template. I will fix this but for now you can work around it by specifying an empty content for the mail.

`mail.setContent(" ")`

**Comment by heihitesh** [comment]
I Tried that too, Didn't work



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/30/21,
08:01:57 PM

**Comment by jakebreen** [comment]
You need to provide the error message returned from the 400 response.

**Comment by heihitesh** [comment]
Hi, I tried the workaround, It worked this time.

But I am getting mail in basic text format (NOT HTML) Like this 
![image](https://user-images.githubusercontent.com/13065741/106374246-31230900-63a7-11eb-90ef-e44942f99f7e.png)


But My Template is similar to this 
![image](https://user-images.githubusercontent.com/13065741/106374256-53b52200-63a7-11eb-8935-d1353de61414.png)

Soruce 
```SendGrid sendGrid = SendGrid.create(getString(R.string.SendGridAPI));
        SendGridMail mail = new SendGridMail();
        mail.addRecipient(email, name);
        mail.setFrom("binaryDev101@gmail.com", "Rent House Manager Pro");
        mail.setSubject("Welcome to Rent House Manager Pro");
        mail.setContent("");                                       //Tried this one too mail.setContent(" ");
        mail.setTemplateId("API_KEY");
    // JSONObject structured into key/value pairs
        final JSONObject templateData = new JSONObject();
        try {
            templateData.put("first_name", "Hitesh Verma");
            mail.setDynamicTemplateData(templateData);
        } catch (JSONException e) {
            e.printStackTrace();
            Log.d("HIT_TAG", "Err : " + e.getMessage());
        }

 SendTask task = new SendTask(sendGrid, mail);
        try {
            SendGridResponse response = task.execute().get();
            toastHelper.toastInfoMsg("Code " + response.getCode()); //this is 202
            Log.d("HIT_TAG", "SendGrid : " + response.getErrorMessage()); //This is now null
        } catch (ExecutionException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
```
Am I Doing Something Wrong?

**Comment by jakebreen** [comment]
I've created a new beta that will fix this problem, you wont need to set an empty content block either... `mail.setContent(" ")`.

`com.github.Jakebreen:android-sendgrid:1.2.2-beta1`

Please try it then reply here.

**Comment by jakebreen** [comment]
Yes I saw it and as I said I have created a beta branch that fixes it. Please test it.

`com.github.Jakebreen:android-sendgrid:1.2.2-beta1`

**Comment by heihitesh** [comment]
Thanks, I'll check it out.
