### ISSUE TITLE
Context doesn't show in the email

### ISSUE THREAD

**Issue by omidmirzajani** [Jakebreen/android-sendgrid#13]
I tried to send a email with this code:
SendGridMail sendGridMail = new SendGridMail();
        sendGridMail.addRecipient("xxxx@outlook.com", "myName");
        sendGridMail.setFrom("yyyy@outlook.ir", "myName");
        sendGridMail.setSubject("Subjet");
        sendGridMail.setContent("MyMessage");
        
But it didn't show "MyMessage" in that email!
Am i doing something wrong?

**Comment by jakebreen** [comment]
Hello, thank you for identifying this, this was a bug.

I've released a new version 1.2.3 `com.github.jakebreen:android-sendgrid:1.2.3`
