### ISSUE TITLE
Unable to attach image

### ISSUE THREAD

**Issue by shehzadraheem** [Jakebreen/android-sendgrid#15]
- I want to attach an image and I have converted it into Uri, but it's not working.
- File attachment is working, but Uri attachment is not working.

**Comment by jakebreen** [comment]
Hello, Can you provide your code please? Are you testing on a device or emulator?

**Comment by shehzadraheem** [comment]
SendGrid sendGrid = SendGrid.create(ThermalogConstants.API_KEY);
                    SendGridMail mail = new SendGridMail();

                    File image = new File("/storage/emulated/0/Pictures/Screenshots/test.png");

                    if (image.getAbsoluteFile().exists()) {
                        try {
                            mail.addAttachment(context,Uri.parse(image.toString()));
                        }catch (IOException e){
                            Log.d(TAG, "sendEmail: "+e);
                        }
                    }
                    mail.addRecipient( employee.getEmailAddress(),  employee.getName());
                    mail.setFrom(dao.getConfiguration(ThermalogConstants.SEND_GRID_SENDER_EMAIL), dao.getConfiguration(ThermalogConstants.SEND_GRID_SENDER_NAME));
                    mail.setSubject( "Alert Warning : Spoilage Alert raised");
                    mail.setContent("Alert Warning : Spoilage Alert raised"
                            + "\nDevice Name : " + dao.getCardTitle(channel.getChannelId())
                            + "\nEquipment Id : " + dao.getCardFromChannelId(channel.getChannelId()).getEquipmentID()
                            + "\nEquipment Type : " + dao.getCardFromChannelId(channel.getChannelId()).getEquipmentType());


                    try {
                        SendTask task = new SendTask(sendGrid, mail);
                        SendGridResponse response = task.execute().get();
                    }catch (Exception e){
                        Log.d(TAG, "sendEmail: "+e);
                    }
                    

I'm using the device for testing.

**Comment by jakebreen** [comment]
Can you provide the logcat when it fails to send the attached uri please.

**Comment by shehzadraheem** [comment]
I have solved it. Thanks
