### ISSUE TITLE
Getting response code 0

### ISSUE THREAD

**Issue by shehzadraheem** [Jakebreen/android-sendgrid#17]
I'm getting response code `0` and `Error parsing error message: Value Unable of type java.lang.String cannot be converted to JSONObject`. It was working perfectly before.  Here is my code

                                SendGrid sendGrid = SendGrid.create(dao.getConfiguration(ThermalogConstants.CONFIG_API_KEY));
                                SendGridMail mail = new SendGridMail();

                                mail.addRecipient("shehzad@gmail.com", "name");
                                mail.setFrom("raheem@gmail.com", "name");
                                mail.setSubject("Alert Warning");

                                String title = "Alert Warning ";
                                SpannableStringBuilder strBold = new SpannableStringBuilder(title);
                                strBold.setSpan(new StyleSpan(Typeface.BOLD),
                                        0, title.length(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);

                                mail.setContent("ok");

                                try {
                                    SendTask task = new SendTask(sendGrid, mail);
                                    SendGridResponse response = task.execute().get();
                                    Log.d("Response", "run: "+response.getCode());
                                    Log.d("Response", "run: "+response.getErrorMessage());
                                } catch (Exception e) {
                                    Log.d(TAG, "sendEmail: " + e);
                                    Log.d("Response", "error: "+e.toString());
                                }
                            }

**Comment by jakebreen** [comment]
Hello.

What version of the library are you using? You said _"It was working perfectly before."_ Did it stop working after you up-versioned the library?

The Error you are receiving `"Error parsing error message:"` is being thrown from the library itself, specifically from the class `ErrorParser::parseError`. It appears as though the error being received from sendgrid is not parse-able to JSON. `Value Unable of type java.lang.String cannot be converted to JSONObject` it's trying to parse the value `"Unable"` which it cant.

I've tried to send a mail through the testapp in the library and it is working for me.

**Can you attach the android debugger and add a debugging line on the library method `parseError` in `ErrorParser` and post what the string value of the variable `response` is?**

![image](https://user-images.githubusercontent.com/22292501/183024671-4dbb40e0-4233-421e-8eb3-92b302eb0c0b.png)

**Comment by shehzadraheem** [comment]
Hi,
I'm getting error on both versions `1.2.3.` and `1.3.0`. `parseError` method gives me this error.

W/System.err: java.net.UnknownHostException: Unable to resolve host "sendgrid.com": No address associated with hostname
W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:1152)
W/System.err:     at com.android.okhttp.Dns$1.lookup(Dns.java:41)
W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
W/System.err:     at uk.co.jakebreen.sendgridandroid.SendGridCall$1.call(SendGridCall.java:28)
W/System.err:     at uk.co.jakebreen.sendgridandroid.SendGridCall$1.call(SendGridCall.java:17)
W/System.err:     at uk.co.jakebreen.sendgridandroid.SendTask.doInBackground(SendTask.java:18)
W/System.err:     at uk.co.jakebreen.sendgridandroid.SendTask.doInBackground(SendTask.java:5)
W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
W/System.err: org.json.JSONException: Value Unable of type java.lang.String cannot be converted to JSONObject
W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:169)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:182)
W/System.err:     at uk.co.jakebreen.sendgridandroid.ErrorParser.parseError(ErrorParser.java:13)
W/System.err:     at uk.co.jakebreen.sendgridandroid.SendGridResponse$Factory.error(SendGridResponse.java:54)
W/System.err:     at uk.co.jakebreen.sendgridandroid.SendTask.doInBackground(SendTask.java:21)
W/System.err:     at uk.co.jakebreen.sendgridandroid.SendTask.doInBackground(SendTask.java:5)
W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
W/System.err: org.json.JSONException: Value Error of type java.lang.String cannot be converted to JSONObject
W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:169)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:182)
W/System.err:     at au.com.thermalog.service.ErrorParser.parseError(EmailService.java:147)
W/System.err:     at au.com.thermalog.service.EmailService$1.run(EmailService.java:111)
W/System.err:     at java.util.TimerThread.mainLoop(Timer.java:562)
W/System.err:     at java.util.TimerThread.run(Timer.java:512)
W/System.err: org.json.JSONException: Value uk.co.jakebreen.sendgridandroid.SendGridResponse@6a66d29 of type java.lang.String cannot be converted to JSONObject
W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:169)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:182)
W/System.err:     at au.com.thermalog.service.ErrorParser.parseError(EmailService.java:147)
W/System.err:     at au.com.thermalog.service.EmailService$1.run(EmailService.java:112)
W/System.err:     at java.util.TimerThread.mainLoop(Timer.java:562)
W/System.err:     at java.util.TimerThread.run(Timer.java:512)

**Comment by jakebreen** [comment]
Has your application specified the internet permission in it's manifest?
`<uses-permission android:name="android.permission.INTERNET"/>`

**Comment by shehzadraheem** [comment]
Yes

**Comment by jakebreen** [comment]
The error you are recieving suggests that there is an issue with your network.

` java.net.UnknownHostException: Unable to resolve host "sendgrid.com": No address associated with hostname`

I'm closing the issue as I don't believe this is a problem with the library.
