### ISSUE TITLE
Cannot get original error cause after exception.

### ISSUE THREAD

**Issue by rrodovalho** [Jakebreen/android-sendgrid#18]
When having connection issue, the error handling does not repass the original exception.

Version: 1.2.3

![Screen Shot 2022-09-20 at 17 57 55](https://user-images.githubusercontent.com/97698462/191363443-222377b5-f118-4e92-91ae-dae92d4cd930.png)
![Screen Shot 2022-09-20 at 17 57 46](https://user-images.githubusercontent.com/97698462/191363450-b8417063-8f65-4297-8313-538057fdb6c8.png)
![Screen Shot 2022-09-20 at 17 57 33](https://user-images.githubusercontent.com/97698462/191363454-436ab3f7-66fa-48f3-a476-ed09c11dc46c.png)
![Screen Shot 2022-09-20 at 17 57 20](https://user-images.githubusercontent.com/97698462/191363456-b01d0cfd-7691-4ef9-bcce-9aeac5c7f392.png)

**Comment by jakebreen** [comment]
Hello.

The exception should be thrown you are right.

I will rectify this.

**Comment by jakebreen** [comment]
1.3.1 released. Exceptions caught during the `SendTask` will get rethrown.

I've changed the API for the `SendTask` it no longer requires a `SendGridMail` object at instantiation, instead pass it to the new `SendTask::send` method.

```
SendTask task = new SendTask(sendGrid);
SendGridResponse response = task.send(mail);
```
