### ISSUE TITLE
setReplyTo actually set from address

### ISSUE THREAD

**Issue by jamiehiggins** [Jakebreen/android-sendgrid#6]
There is a bug in SendGridMail that prevents the replyTo functionality working.

public void setReplyTo(@NonNull String email, @Nullable String name) {
        if (name == null)
            name = EMPTY;
        from.put(email, name);
    }

The last line should be replyTo.put

**Comment by jakebreen** [comment]
Hello,

I've published a fix onto the latest version, 1.2.1
`com.github.jakebreen:android-sendgrid:1.2.1`

If there anymore issues you find let me know, Thanks!
